name: honeycrisp
version: 0.0.0

category: Web
description: Honeycrisp is an Apple News API client.
extra-source-files:
  - package.yaml
  - stack.yaml
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Apple News API client

dependencies:
  aeson: '>= 1.3.1 && < 1.4'
  base: '>= 4.11.1 && < 4.12'
  bytestring: '>= 0.10.8 && < 0.11'
  cryptonite: '>= 0.25 && < 0.26'
  http-client: '>= 0.5.13 && < 0.6'
  http-types: '>= 0.12.1 && < 0.13'
  memory: '>= 0.14.16 && < 0.15'
  microlens: '>= 0.4.9 && < 0.5'
  network-uri: '>= 2.6.1 && < 2.7'
  text: '>= 1.2.3 && < 1.3'
  time: '>= 1.8.0 && < 1.9'
  uuid: '>= 1.3.13 && < 1.4'
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

library:
  exposed-modules: Honeycrisp
  source-dirs: library
